### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by jaanos** [vrle/Profit#1]
ER diagram vstavite v `README.md` tako, da na želeno mesto postavite:

``` markdown
![ER diagram](ER.png)
```

Med oglatimi oklepaji je besedilo, ki se prikaže, ko gre miška čez sliko, v okroglih oklepajih pa je relativna pot do slike. Več o oblikovanju Markdown si lahko preberete na

https://guides.github.com/features/mastering-markdown/

Kot smo se že pogovarjali, je `Stock` šibka entiteta, določena s podjetjem - do relacije `issued` naj gre torej dvojna (ali debela) puščica, pa tudi sama relacija naj ima debelo obrobo. Poleg tega je atribut `ticker` odveč, saj je impliciran z relacijo (v bazi seveda ta stolpec bo kot tuji ključ na tabelo podjetij).

Entiteta `Portfolio` je prav tako prikazana kot šibka entiteta, a ni jasno, od česa naj bi še bila odvisna. Če prav razumem, bi morala biti običajna entiteta, z relacijo več-na-več, kot je sicer že prikazana.

**Comment by jaanos** [comment]
Vidim, da ste popravili. Nimam drugih pripomb, tako da zapiram zadevo.

**Comment by jaanos** [comment]
Še to sem opazil: iz šibke entitete `Stock` v relacijo `issued` naj gre seveda puščica.

**Comment by vrle** [comment]
Pozdravljeni,
smo popravili.
