### ISSUE TITLE
uvoz podatkov na PostgreSQL

### ISSUE THREAD

**Issue by VidStarc** [vrle/Profit#3]
Pozdravljeni!
Naredili smo tabele na naši bazi v PostreSQL z ukazom dbSendQuery(conn, build_sql("CREATE TABLE ... ) v programu Rstudio. Sedaj pa nas zanima kako uvoziti podatke iz programa Rstudio na našo bazo v PostreSQL. Torej katera funkcija nam podatke iz razpredelnic, ki smo jih sestavili v programu Rstudio, pošlje na bazo (namreč poskusili smo s funkcijo dbWriteTable, a nam nikakor ne uspe).

**Comment by jaanos** [comment]
Funkciji `dbWriteTable` podajte še parameter `append = TRUE`. Tako ta ne bo poskušala narediti nove tabele, pač pa bo dodala podatke v obstoječo tabelo. Pazite seveda, da se imena stolpcev v R-jevi razpredelnici ujemajo z imeni stolpcev v tabeli. Druga možnost je pa seveda ta, da sami sestavljate ukaze `INSERT`.

Če boste z `dbWriteTable` vstavljali v tabelo s stolpcem tipa `SERIAL` ter boste potem želeli vstavljati podatke, ki se navezujejo na vstavljene vrstice, bo treba seveda pridobiti dodeljene ID-je. Za pridobivanje in sestavljanje podatkov lahko uporabite kar `dplyr` - poglejte si zadnji komentar pri BraMira/Mirjam-Spela#5.

**Comment by vrle** [comment]
Pozdravljeni,
še zmeraj imamo težave pri uvozu podatkov. Zato Vas prosimo, če lahko pregledate kodo za uvoz v baza.r.

Lep pozdrav.
Rok

**Comment by jaanos** [comment]
Pazite, da se število stolpcev v tabeli, kamor vstavljate, ujema s številom stolpcev razpredelnice s podatki. V razpredelnici `Company` imate tako stolpec `X`, ki se ga želite znebiti:

``` R
dbWriteTable(conn, name="company", # pazite na velikost črk v imenu tabele!
             Company %>% select(-X), append=T, row.names=FALSE)
```

Glede na to, da imate v stolpcu `MarketCap` decimalne vrednosti, bo treba spremeniti tudi tip ustreznega stolpca v tabeli `company`, npr. na `REAL` ali `NUMERIC` (če vas zanima razlika, si poglejte v dokumentacijo za PostgreSQL). Poleg tega imate v `Company.csv` v tem stolpcu eno vrednost v eksponentni notaciji - poskrbite, da bo tudi to število v decimalni notaciji, da se bo stolpec pravilno interpretiral kot številski.

Opažam še, da se podatki v `Sector.csv` ne ujemajo s specifikacijo tabele `sector` - tam je `type` glavni ključ, v datoteki pa se isti tip pojavi večkrat. Premislite, kaj tukaj zares želite - meni izgleda, kot da bi lahko stolpce iz tabele `sector` vključili v tabelo `company` (v tem primeru seveda pred vstavljanjem že v R-ju sestavite združeno tabelo, npr. z `inner_join`).

**Comment by nolimal** [comment]
Spoštovani, 

zanima nas kako lahko združimo več podatkov 15-ih delnic v eno skupno tabelo Stock.

**Comment by jaanos** [comment]
Če prav razumem, želite združiti podatke iz datoteke `stockdata.RData`. Če prav razumem, bi šlo nekako tako:

``` R
library(dplyr)
load("2. podatki/stockdata.RData")
tickers <- stockData$.getSymbols %>% names()
all.tickers <- tickers %>% lapply(. %>% {
    data <- data.frame(stockData[[.]])
    names(data) <- c("Open", "High", "Low", "Close", "Volume", "Adjusted")
    data.frame(ticker = factor(., levels = tickers),
               index = attr(stockData[[.]], "index"),
               data)
  }) %>% bind_rows()
levels(all.tickers$ticker) <- levels(all.tickers$ticker) %>% trimws()
```

**Comment by nolimal** [comment]
Najlepša hvala za prejšnji namig. Sedaj, ko smo uvozili tabelo Stock in ker želimo generirati tabelo Portfolio imamo sistemsko vprašanje. Portfolio bo kazalo gibanje premoženja z neko strategijo vlaganja (npr. na začetku vsakega meseca kupimo 3 po donosih prejšnjega meseca najboljše delnice in jih držimo do konca meseca). To bi znali narediti v RStudiu in potem uvoziti podatke iz CSV datoteke na našo bazo. Ali druge skupine tovrstne zadeve rešujejo preko SQL stavkov? V mislih imam stavke SELECT?.... Torej ali bi se pričakovalo delati tako: v baza.R in nato dodamo prazno tabelo (.....dbSendQuery(conn, build_sql("CREATE TABLE portfolio.....)), in nato  recimo odpremo novo mapo 4. vrednotenje in naredimo povezavo z bazo podobno  in nato ustvarimo funkcijo, ki generira podatke z (dbSendQuery(conn, build_sql("SELECT \* FROM stock WHERE....))??? Ali kakšnen je zaželjen postopek z SQL?

**Comment by jaanos** [comment]
Lahko delate neposredno z SQL stavki, lahko si pa pomagate s knjižnico dplyr ter poizvedbe sestavljate z ukazi, kot so `filter`, `select`, `arrange`, `group_by`, `summarise`, `inner_join`, `left_join` itd.

Če boste delali neposredno z SQL, potem je za poizvedbe potrebno uporabiti ukaz `dbGetQuery` - ta namreč tudi vrne želeno razpredelnico.
