### ISSUE TITLE
aplikacija shiny

### ISSUE THREAD

**Issue by VidStarc** [vrle/Profit#4]
Pozdravljeni!
V datoteki 6.shiny1 delamo aplikacijo za tabelo Stock. In sicer si želimo naslednje:
1. Ko kliknemo All se prikaže Close price za vse delnice (to smo že naredili)
2. Ko kliknemo katerokoli delnico se prikaže gibanje close price skozi obdobje, torej na x osi bi imeli datum, na y osi pa close price (tega ne znamo narediti, zato bi prosili za pomoč)
3. Radi bi imeli še en sidebar kjer bi izbirali različne vrednosti (ne samo close, ampak tudi open, high, low, adjusted, change) -tega tudi ne znamo, zato bi tudi pri tem delu prosili za pomoč.
V naprej se Vam zahvaljujemo.

**Comment by jaanos** [comment]
Najprej bi vas prosil, da daste uporabniku _javnost_ pravico dostopa do baze (poglejte si na spletni učilnici), potem pa v Shiny aplikacijah namesto `auth.R` vključite npr. datoteko `auth_public.R` s podatki za povezavo z uporabnikom _javnost_. Opozoril bi še na velikost črk v imenu imenika `2. podatki` pri branju datoteke `Portfolio.csv` v programu `baza.r` - ta ima male črke, zato naj bo tako tudi v programu (tako kot je že drugod).

Opažam še, da je stolpec `index` v tabeli `stock` tipa `REAL`, kar v praksi pomeni, da boste imeli težave s primerjanjem vrednosti (npr. pridobivanje zadnjih vrednosti). Glede na to, da gre tukaj za timestampe (čas v sekundah, pretečen od 1. januarja 1970), bo bolje, če tip spremenite na `TIMESTAMP`, vrednosti pa pred uvozom pretvorite v datume:

``` R
Stock$index <- Stock$index %>% as.POSIXct(origin="1970-01-01")
```

Da boste lahko izbrali vrednost na osi y, v `ui.R` dodajte izbirnik, npr.

``` R
selectInput("value", "Vrednost", 
                    choices=c("open", "high", "low",
                              "close", "volume", "adjusted"),
                    selected = "close")
```

Če želite prikazati kakšno drugo ime, vektorju za `choices` dajte še imena - npr. `c("Open" = "open", ...)` bo prikazalo `Open`, strežniku se pa pošlje vrednost `"open"`.

Sedaj lahko v `server.R` izrišete ustrezen graf, npr.

``` R
  output$stock <- renderPlot({
    tab <- tbl.stock
    if (input$ticker == "All") { # prikazujemo vse delnice
      max.index <- tab %>% summarise(max(index)) %>% data.frame() %>% .[,1] %>%
        strftime() # pridobimo čas najnovejših vrednosti in samo te prikažemo
      graf <- ggplot(tab %>% filter(index == max.index) %>% data.frame(),
             aes_string(x = "ticker", y = input$value)) +
        geom_bar(stat = "identity")
    } else { # prikazujemo posamezno delnico
      graf <- ggplot(tab %>% filter(ticker == input$ticker) %>% data.frame(),
                     aes_string(x = "index", y = input$value)) + geom_line()
    }
    graf + ggtitle(input$ticker) + xlab("Ticker") + ylab(input$value)
  })
```

**Comment by nolimal** [comment]
Spoštovani, 

zanima nas, kako bi lahko naredili aplikacijo, ki bi nam na podlagi datuma in izbranega portfelja (portfolio1, portfolio3, portfolio7) vrnila asset movement (spremenljivka am v tabelah) in za vsak portfelj 1,3,7 vrnila katere ticker-je vključimo tisti dan. 

Lp
M.

**Comment by jaanos** [comment]
Najprej bi predlagal, da imate vse portfelje v isti tabeli - obstoječim stolpcem torej dodajte še en stolpec z indeksom portfelja. Potem boste podatke za izbrani portfelj dobili s filtriranjem te tabele po izbranem indeksu. Ne pozabite tudi, da so tickerji (morda bi bilo bolje, če bi stolpcu bilo ime kar `ticker`) referenca na `company` (pri uvozu pazite na presledke pred imeni tickerjev - znebite se jih lahko s funkcijo `trimws`). Koristno bo tudi, če za trojico (indeks portfelja, datum, ticker) določite še omejitev `UNIQUE`.

Če prav razumem, bi potem za podani portfelj in datum radi dobili vsak ticker za podani datum skupaj z asset movementom. Potem bi šlo nekako tako:

``` R
tbl.portfolio <- tbl(conn, "portfolio") # tabela s portfelji

data <- tbl.portfolio %>% filter(index == indeks.portfelja, date2 == datum) %>%
  select(ticker, am) %>% data.frame()
```

Indeks portfelja in datum boste seveda pridobili iz Shinyjevih gradnikov. Potem lahko dobljene podatke prikažete na želeni način.

**Comment by VidStarc** [comment]
Prav pri združevanju imamo problem, ker nismo vedeli kako združiti treh tabel z različnimi velikostmi, namreč tabela portfolio1 pove katero delnico zberemo v naši strategiji na točno določen dan (tisti z maksimalnim change-om), portfolio 3 pove katere tri delnice zberemo na točno določen dan (zato so tudi vrstice te tabele nastavljene tako, da je isti dan v treh vrsticah) in tabela portfolio7 podobno.

**Comment by jaanos** [comment]
Podatki v datotekah CSV so že v obliki, ki je primerna za vstavljanje v skupno tabelo - potrebno bo dodati le še indeks portfelja. Potem lahko v `baza.r` naredite nekaj takega:

``` R
portfolio <- rbind(data.frame(index = 1, Portfolio1),
                   data.frame(index = 3, Portfolio3),
                   data.frame(index = 7, Portfolio7)) %>% select(-X)
dbWriteTable(conn, name="portfolio",portfolio, append=T, row.names=FALSE)
```

Tukaj sem odstranil stolpec z ID-ji, saj se čez različne tabele ponavljajo. Tako so lahko indeks portfelja, datum in ticker lahko kar glavni ključ namesto `UNIQUE`. Če pa bi želeli delati reference na posamezne vrstice tabele `portfolio`, pa lahko seveda ta ID (tipa `SERIAL`) pustite v tabeli - podatke (brez ID) lahko še vedno vnesete tako, da se imena stolpcev razpredelnice ujemajo z imeni stolpcev tabele v bazi in pri `dbWriteTable` odstranite parameter `row.names=FALSE`. Vrednosti stolpca `id` se bodo potem samodejno generirale.

**Comment by nolimal** [comment]
Spoštovani, 

naprošamo Vas, da malo pogledate 7. shiny mapo, ker ne znamo popraviti, da bi delovalo.

Lp, 
M.

**Comment by jaanos** [comment]
Najprej, v `ui.R` vam na koncu manjka zaklepaj. Prav tako spremenljivka `startDate` ni definirana - verjetno bo najlažje, če kar sami podaste datum (v obliki `2014-12-31`). Če bi pa želeli ta datum dobiti kot rezultat poizvedbe v bazi, bi morali izbirnik datuma narediti v `server.R` s funkcijo `renderUI` in ga prikazati v `ui.R` z `uiOutput`.

Če prav razumem, želite za izbrani časovni interval narisati graf, ki prikazuje vrednosti stolpca `am` za vsako delnico v portfelju. Graf za vse delnice lahko narišete tako:

``` R
    data <- tab %>% filter(index == input$index,
                           date2 >= input$daterange[1],
                           date2 <= input$daterange[2]) %>%
      select(date2, sel_tickers, am) %>% data.frame()
    data$date2 <- as.Date(data$date2)
    ggplot(data, aes(x = date2, y = am, color = sel_tickers)) +
      geom_line() + xlab("Date") + ylab("Asset Movement")
```

Da se bo graf pravilno izrisal, mora stolpec `date2` v tabeli `portfolio` biti tipa `DATE`. Tabelo `portfolio` torej ustvarite s `CREATE TABLE` namesto tabel `portfolio1`, `portfolio3` in `portfolio7`, preden vanjo vstavite podatke (glejte zgornji komentar).

Ni mi sicer najbolj jasno, kaj ste želeli z drugim izbirnim poljem. Z zgornjo kodo se za vsak ticker izriše svoja črta - ne vem sicer, če je to to, kar ste hoteli. Če ste želeli omejiti število delnic, za katere se pokažejo podatki, se seveda gre vprašati, katere so tiste delnice, za katere to želite.

**Comment by VidStarc** [comment]
Ok, naredili smo tabelo portfolio s funkcijo CREATE TABLE, druge tri tabele pa smo še pustili v primeru da bi nam kdaj prišle prav. 
aplikacija portfolio pa ne deluje in ne znamo kaj bi bilo narobe. piše pa: no applicable method for 'escape' applied to an object of class "data.frame".
Morda se tudi nismo razumeli, kaj bi mi prikazali v tej aplikaciji. Torej, za izbrani časovni interval in izbrani Portfelj bi radi prikazali vrednosti stolpca am, pri tem pa če se da še izpisali tickerje, ki smo jih na določeni dan izbrali.

**Comment by jaanos** [comment]
Ali ste prepričani, da imate zadnjo verzijo na gitu? Meni aplikacija ne deluje zaradi `startDate` (glejte prejšnji komentar); če to popravim, mi javi napako zaradi neobstoječega stolpca `ticker` (stavek `if` je odveč v `server.R`). Sicer pa ta napaka pomeni, da ste v poizvedbo (npr. k `filter`) dali razpredelnico. Če imate razpredelnico z enim samim podatkov, ga lahko potegnete ven z ustreznim indeksom (npr. `razpredelnica[1,1]`).

Kar se tiče tabele `portfolio`, naj bo `sel_tickers` referenca na `company` (glejte moj drugi komentar - treba bo nekoliko popraviti še uvoz). Ne pozabite dati pravic uporabniku _javnost_ za tabelo `portfolio`.

Kako ste mislili prikazati želene podatke? Podatek `am` imate za vsak dan pri izbranem številu delnic, ki se pa čez čas razlikujejo - naj se torej prikaže njegovo gibanje za vsako delnico posebej, ali skupaj? Trenutno imate na izbiro časovni interval - za kateri dan naj se prikažejo izbrani tickerji? Bi to morali podati posebej?

**Comment by VidStarc** [comment]
Imamo zadnjo verzijo na gitu, startDate pa kličemo mi iz uvoza, ker ga imamo že tam definiranega. Če pa je to problem, pa lahko napišemo na roko štartni datum. 
referenco na company bomo še uredili (verjetno to ne vpliva na končno aplikacijo, ne?)

Podatke bi želeli prikazati tako, da ko izberemo željeno časovno obdobje, se prikaže gibanje vrednosti am-ja v tem časovnem obdobju in sicer npr. za dan 2015-01-05 in portfolio3 je vrednost am-ja vsota prvih treh vrstic (saj prve tri vrstice prikazujejo isti datum), npr. za portfolio7 je to vsota prvih sedmih vrstic itd.

**Comment by vrle** [comment]
Pozdravljeni,

dodatno nas še zanima, kako bi lahko v aplikaciji 5. shiny_nov naredili v sidebaru možnost izbire close, open, volume,... (to znamo), s tem, da bi bil pod tem izbirnikom še checkbox z vsemi tickerji (tega ne znamo). Torej bi lahko z aplikacijo primerjali close, open in ostale vrednosti za poljubno število tickerjev.
Ko bi npr. izbrali "open" in odkljukali 5 tickerjev, bi se nam izrisalo 5 grafov, na katerem bi vsak kazal gibanje vrednosti "open" za posamezno delnico.

**Comment by jaanos** [comment]
Shiny aplikacijo se načeloma kliče "iz nule", tako da prostih spremenljivk ne sme biti.

Graf, ki prikazuje gibanje vsote `am` za posamezen dan, lahko prikažete tako:

``` R
  output$portfolio <- renderPlot({
    tab <- tbl.portfolio
    data <- tab %>% filter(index == input$index,
                                   date2 >= input$daterange[1],
                                   date2 <= input$daterange[2]) %>%
      group_by(date2) %>% summarise(am = sum(am)) %>% data.frame()
    data$date2 <- as.Date(data$date2)
    graf<-ggplot(data, aes(x = date2, y = am)) +
      geom_line() + xlab("Date") + ylab("Asset Movement")
    graf
  })
```

Seveda se tu izgubi podatek o tem, kateri tickerji so izbrani na določen dan - če boste hoteli to informacijo, jo bo potrebno pridobiti posebej.

**Comment by nolimal** [comment]
Kako bi pa naredili aplikacijo, ki nam na podlagi izbranega datuma in izbranega portfelja (indeksi so 1,3,7) povedala katere Tickerje smo tisti dan uporabili?

**Comment by jaanos** [comment]
Namesto checkboxov predlagam, da uporabite kar `selectInput` s parametrom `multiple = TRUE` - tako boste lahko izbrali več tickerjev, ki jih potem v `server.R` dobite kot vektor. Namesto, da potem za vsakega rišete svoj graf, lahko na isti graf daste črto svoje barve, tako da pri `aes` podaste parameter `color = ticker` (kjer je `ticker` ime stolpca, po katerem ločite črte).

Pazite na to, da dplyr različno obravnava vektorje dolžine 1 in daljše vektorje, zato bo treba najbrž filtriranje po tickerjih obravnavati s stavkom `if`. Lahko si pomagate tudi z ukazom `validate` (glejte BraMira/Mirjam-Spela#10), da izpišete ustrezno obvestilo v primeru napačne izbire (npr. ko ni izbran noben ticker).

Za prikaz tickerjev na določen dan v portfelju pa enostavno dodajte polje za izbiro datuma (ali pa tega nekako izpeljite iz intervala) ter potem filtrirajte po tem datumu in izberite stolpec `sel_tickers`. Potem to nekako prikažite (npr. s tekstovnim poljem).

**Comment by VidStarc** [comment]
odgovarjam na zadnji odstavek:
s tekstovnim poljem smo poizkušali, ampak ne gre tako kot smo si zamislili. Najboljše bi bilo če bi se za dano časovno obdobje izrisala tabela, ki bi prikazala za te dneve in za vsak dan katere tickerje zberemo

**Comment by jaanos** [comment]
Potem bi bilo najbolje, da poberete seznam tickerjev (npr. ločene z vejico) skupaj z vsoto `am`. Tako boste isto poizvedbo delali za dve stvari, tako da se jo izplača narediti samo enkrat. Tukaj pomaga funkcija `reactive`, ki poskrbi za shranjevanje vmesnih rezultatov - tako ni potrebno, da bi naredili dve poizvedbi, pač pa se tako za graf kot za tabelo uporabijo rezultati iste poizvedbe.

``` R
  portfolio.data <- reactive({
    data <- tbl.portfolio %>% filter(index == input$index,
                                     date2 >= input$daterange[1],
                                     date2 <= input$daterange[2]) %>%
      group_by(date2) %>%
      summarise(am = sum(am),
                tickers = paste(sel_tickers, collapse = ",")) %>%
      arrange(date2) %>% data.frame()
    data$date2 <- as.Date(data$date2)
    data
  })

  output$portfolio <- renderPlot({
    data <- portfolio.data()
    graf <- ggplot(data, aes(x = date2, y = am)) +
      geom_line() + xlab("Date") + ylab("Asset Movement")
    graf
  })

  output$tickers <- renderTable({
    data <- portfolio.data()
    tickers <- data$tickers %>% strsplit(",") %>% as.data.frame() %>% t()
    rownames(tickers) <- NULL
    df <- data.frame(as.character(data$date2), tickers)
    names(df) <- c("Datum", paste("Ticker", 1:input$index))
    df
  })
```

Ta koda bo delovala, če se v rezultatih dejansko za vsak datum pojavi enako število delnic. Če temu ni tako, bo treba pred `as.data.frame` to ugotoviti in ustrezno popraviti vektorje v dobljenem seznamu. Da prikažete tabelo, na želeno mesto v `ui.R` dodajte `tableOutput("tickers")`. Za lepši izpis tabele lahko uporabite tudi `DT::renderDataTable` in `DT::dataTableOutput`.

Še to: kljub uporabi `reactive` zna biti aplikacija vseeno počasna. Morda lahko zožate privzeti časovni interval, da bo hitreje pokazalo prvi graf in tabelo.
