### ISSUE TITLE
narejen projekt

### ISSUE THREAD

**Issue by VidStarc** [vrle/Profit#5]
Pozdravljeni!
Najprej se Vam zahvaljujemo za vso pomoč pri projektu. 
Sedaj pa Vas samo še prosimo, da nam naš projekt pregledate, podate mnenje, da gremo lahko potem že na zagovor.

**Comment by jaanos** [comment]
Projekt izgleda v redu, tako da se lahko s profesorjem domenite za termin zagovora. Do takrat lahko naredite še nekaj lepotnih popravkov:
- Da se bodo lepo prikazale barve stolpcev, pri `aes` uporabite parameter `fill` namesto `color`. Ta parameter lahko (poleg `color`) uporabite tudi pri grafu v drugem zavihku, da se bo legenda lepše prikazala.
- V tretjem zavihku popravite tudi oznako na osi x, ko prikazujete stolpčni diagram (`xlab` z ustrezno oznako prištejte v vsaki veji stavka `ìf`).
- V zadnjem zavihku je `index` številska spremenljivka, zato se prikaže zvezna lestvica. Glede na to, da imate samo tri indekse, bo seveda bolj smiselno, če se črte prikažejo v različnih barvah. To lahko dosežete tako, da `index` pretvorite v faktor, obenem pa poskrbite za ustrezen naslov legende oziroma jo odstranite, ko prikazujete en sam indeks:

``` R
  output$portfolio <- renderPlot({
    if (input$index == "All") {
      guide <- guide_legend(title = "Index")
    } else {
      guide <- FALSE
    }
    ggplot(portfolio.data(),
           aes(x = date2, y = am, color = factor(index), group = index)) +
      geom_line() + xlab("Date") + ylab("Asset Movement") +
      scale_color_discrete(guide = guide)
  })
```

**Comment by VidStarc** [comment]
Ok popravljeno.
